development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c84c9b89ae3e328dce673cfffee2722c@soldierfish.redistogo.com:9919/
  channel_prefix: flatchat_api_production
